In [1]:
import pandas as pd

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19260\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv(r"../data/newborn_health_monitoring_with_risk.csv")
df.head()

,baby_id,name,gender,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,date,age_days,weight_kg,...,oxygen_saturation,feeding_type,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score,immunizations_done,reflexes_normal,risk_level
0,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-10,1,3.28,...,98,Formula,11,9,0,4.2,7.0,Yes,Yes,At Risk
1,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-11,2,3.35,...,99,Formula,11,5,2,10.6,NaN,No,No,At Risk
2,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-12,3,3.35,...,97,Breastfeeding,7,6,5,9.8,NaN,No,No,Healthy
3,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-13,4,3.48,...,97,Mixed,11,8,4,8.1,NaN,No,Yes,Healthy
4,B001,Sara,Female,40.2,3.3,50.0,31.9,2024-12-14,5,3.50,...,96,Breastfeeding,11,7,1,11.6,NaN,No,Yes,At Risk

In [5]:
df.isnull().sum()

baby_id                           0
name                              0
gender                            0
gestational_age_weeks             0
birth_weight_kg                   0
birth_length_cm                   0
birth_head_circumference_cm       0
date                              0
age_days                          0
weight_kg                         0
length_cm                         0
head_circumference_cm             0
temperature_c                     0
heart_rate_bpm                    0
respiratory_rate_bpm              0
oxygen_saturation                 0
feeding_type                      0
feeding_frequency_per_day         0
urine_output_count                0
stool_count                       0
jaundice_level_mg_dl              0
apgar_score                    2900
immunizations_done                0
reflexes_normal                   0
risk_level                        0
dtype: int64

In [6]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
# Heart Rate
df = df[(df["heart_rate_bpm"] > 50) & (df["heart_rate_bpm"] < 250)]

# Respiratory Rate
df = df[(df["respiratory_rate_bpm"] > 10) & (df["respiratory_rate_bpm"] < 100)]

# Oxygen Saturation
df = df[(df["oxygen_saturation"] >= 50) & (df["oxygen_saturation"] <= 100)]

# Temperature
df = df[(df["temperature_c"] > 30) & (df["temperature_c"] < 45)]

In [10]:
df.describe()

,gestational_age_weeks,birth_weight_kg,birth_length_cm,birth_head_circumference_cm,age_days,weight_kg,length_cm,head_circumference_cm,temperature_c,heart_rate_bpm,respiratory_rate_bpm,oxygen_saturation,feeding_frequency_per_day,urine_output_count,stool_count,jaundice_level_mg_dl,apgar_score
count,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000,2993.000000
mean,38.878617,3.204688,49.724223,34.127030,15.507852,3.669689,50.505546,34.438223,37.002639,139.684263,39.427999,97.464751,9.451052,6.470765,2.445707,4.159338,8.400000
std,1.569741,0.561225,2.142884,1.487414,8.658557,0.621009,2.195692,1.502034,0.310742,10.134665,4.998420,1.035553,1.707083,1.701062,1.698677,2.856780,0.211627
min,35.400000,1.860000,45.100000,31.200000,1.000000,1.790000,45.000000,31.100000,35.800000,100.000000,23.000000,94.000000,7.000000,4.000000,0.000000,0.000000,7.000000
25%,37.800000,2.870000,48.400000,32.900000,8.000000,3.220000,49.100000,33.300000,36.800000,133.000000,36.000000,97.000000,8.000000,5.000000,1.000000,2.500000,8.400000
50%,38.800000,3.150000,49.500000,34.100000,16.000000,3.660000,50.400000,34.400000,37.000000,140.000000,39.000000,97.000000,9.000000,6.000000,2.000000,3.300000,8.400000
75%,40.100000,3.620000,51.000000,34.800000,23.000000,4.100000,51.800000,35.300000,37.200000,146.000000,43.000000,98.000000,11.000000,8.000000,4.000000,4.300000,8.400000
max,43.000000,4.470000,55.800000,38.100000,30.000000,5.410000,57.400000,38.700000,38.100000,173.000000,57.000000,100.000000,12.000000,9.000000,5.000000,15.000000,10.000000

In [13]:
df.to_csv("../data/cleaned_data.csv", index=False)

In [14]:
df.shape

(2993, 25)